alpha = "Î±"
betta = "Î²"
gamma = "Î³"
delta = "Î´"

alien = "ğŸ‘½"
bug = "ğŸ›"
check = "ğŸ—¸"
dragon = "ğŸ‰"
fire = "ğŸ”¥"
fireworks = "ğŸ†"
key = "ğŸ”‘"
mind_explode = "ğŸ¤¯"
moai = "ğŸ—¿"
party_face = "ğŸ¥³"
penguin = "ğŸ§"
rocket = "ğŸš€"
shit = "ğŸ’©"
sloth = "ğŸ¦¥"
snail = "ğŸŒ"
thumbs_up = "ğŸ‘"
